name: stitch_mumbai_pool_transit_ui
description: TogetherRide - Mumbai Pool Transit & Carpooling Mobile Application for daily urban commuters.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  http: ^1.2.0
  supabase_flutter: ^2.8.0
  flutter_map: ^8.3.2
  latlong2: ^0.10.1
  google_sign_in: ^7.2.0
  google_maps_flutter: ^2.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - sahay/DESIGN.md
    - assets/images/
